boot:
  namespaces:
  os:
    ubuntu:
      repo: quay.io/boot/ubuntu
      versions:
      - "22.04"
#      resources:
#        limits:
#          cpu: 500m
#          memory: 1Gi
#        requests:
#          cpu: 500m
#          memory: 1Gi
    alpine:
      repo: quay.io/boot/alpine
      versions:
      - "3.18"
#      resources:
#        limits:
#          cpu: "0.5"
#          memory: 1Gi
#        requests:
#          cpu: "0.5"
#          memory: 1Gi
    ubi:
      repo: quay.io/boot/ubi
      versions:
      - "9.2"
#      resources:
#        limits:
#          cpu: "0.5"
#          memory: 1Gi
#        requests:
#          cpu: "0.5"
#          memory: 1Gi
  jumphost:
    user:
      name: jump
      uid: 10000000
      gid: 10000000
    port: 2222
    authorizedKeys: []
    trustedUserCAKeys: []
    hostCertificate:
  service:
    annotations:
    labels:
    externalIPs:
  serviceAccount:
    annotations:
    labels:
  deployment:
    annotations:
    labels:
    affinity:
    tolerations:
    nodeSelector:
    strategy:
    priorityClassName:
    replicas: 2
    terminationGracePeriodSeconds: 300
    pods:
      annotations:
      labels:
    containers:
      boot:
        image:
          repo: aerokube/boot
          tag:
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
      jumphost:
        image:
          repo: aerokube/jumphost
          tag:
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
      keygen:
        image:
          repo: aerokube/keygen
          tag:
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
      reloader:
        image:
          repo: aerokube/reloader
          tag:
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
