---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ssh-keys
  namespace: {{ .Release.Namespace }}
stringData:
  {{- with .Values.boot.jumphost.hostCertificate }}
  ssh_host_key-cert.pub:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  user_ca.pub: |
  {{- range $k := .Values.boot.jumphost.trustedUserCAKeys }}
    {{ $k }}
  {{- end }}
  authorized_keys: |
  {{- range $k := .Values.boot.jumphost.authorizedKeys }}
    {{ $k }}
  {{- end }}
