---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.boot.serviceAccount.annotatios }}
  annotations:
    {{- toYaml . | nindent 4 -}}
  {{- end }}
  {{- with .Values.boot.serviceAccount.labels }}
  labels:
    {{- toYaml . | nindent 4 -}}
  {{- end }}
