---
apiVersion: v1
kind: Service
metadata:
  {{- with .Values.boot.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 -}}
  {{- end }}
  {{- with .Values.boot.service.labels }}
  labels:
  {{- toYaml . | nindent 4 -}}
  {{- end }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: ssh
    protocol: TCP
    port: {{ .Values.boot.jumphost.port }}
  {{- with .Values.boot.service.externalIPs }}
  externalIPs:
  {{- range . }}
  - {{ . }}
  {{- end }}
  {{- end }}
  type: {{ .Values.boot.service.type | default "LoadBalancer" }}
{{- $namespaces := .Values.boot.namespaces }}
{{- if not $namespaces }}
{{- $namespaces = list .Release.Namespace }}
{{- end }}
{{- range $namespace := $namespaces }}
---
apiVersion: v1
kind: Service
metadata:
  name: vm
  namespace: {{ $namespace }}
spec:
  selector:
    boot.aerokube.com/type: virtualmachine
  clusterIP: None
{{- end -}}
