name: build

on:
  workflow_dispatch:
    inputs:
      regenerateIndex:
        description: "Regenerate index from S3 archives"
        type: boolean
        required: false
  push:
    branches:
      - master

jobs:
  build-chart:
    runs-on: ubuntu-latest
    if: github.repository == 'aerokube/charts'
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: ci/test.sh

      - name: Build
        run: |
          git fetch --tags
          export COMMIT=$(git rev-parse --short HEAD)
          ci/build.sh $COMMIT ${{ github.event.inputs.regenerateIndex != '' && github.event.inputs.regenerateIndex || 'false' }} unstable
        env:
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.S3_REGION }}

      - name: Send output to S3 bucket
        working-directory: ./output
        run: aws s3 cp . --endpoint=${{ secrets.S3_ENDPOINT }}  s3://${{ secrets.S3_BUCKET_NAME }} --recursive --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.S3_REGION }}
